copy "..\TaskBase\bin\x86\Release\AILinkFactoryAuto.Base.dll" "..\release_studio"
copy "..\TaskBase\bin\x86\Release\AILinkFactoryAuto.Base.pdb" "..\release_studio"
copy "..\TaskBase\bin\x86\Release\AILinkFactoryAuto.Base.dll" "..\release_studio"
copy "..\TaskBase\bin\x86\Release\AILinkFactoryAuto.Base.pdb" "..\release_studio"
copy "..\WinFormsUI\bin\x86\Release\WeifenLuo.WinFormsUI.Docking.dll" "..\release_studio"
copy "..\WinFormsUI\bin\x86\Release\WeifenLuo.WinFormsUI.Docking.pdb" "..\release_studio"
copy "..\TaskAtCommand\bin\x86\Release\AILinkFactoryAuto.Dut.AtCommand.dll" "..\release_studio"
copy "..\TaskAtCommand\bin\x86\Release\AILinkFactoryAuto.Dut.AtCommand.pdb" "..\release_studio"
copy "..\Instrument\bin\x86\Release\AILinkFactoryAuto.Instrument.Far.dll" "..\release_studio"
copy "..\Instrument\bin\x86\Release\AILinkFactoryAuto.Instrument.Far.pdb" "..\release_studio"
copy "..\Demo\bin\x86\Release\AILinkFactoryAuto.GenJts.Demo.dll" "..\release_studio"
copy "..\Demo\bin\x86\Release\AILinkFactoryAuto.GenJts.Demo.pdb" "..\release_studio"
copy "..\AILinkFactoryAuto\bin\x86\Release\AILinkFactoryAutoStudio.exe" "..\release_studio"
copy "..\AILinkFactoryAuto\bin\x86\Release\AILinkFactoryAutoStudio.pdb" "..\release_studio"
copy "..\lib\Newtonsoft.Json.dll" "..\release_studio"
copy "..\lib\Newtonsoft.Json.xml" "..\release_studio"
copy "..\lib\MesDll.dll" "..\release_studio"
copy "..\lib\log4net.2.0.8\lib\net40-full\log4net.dll" "..\release_studio"
copy "..\lib\log4net.2.0.8\lib\net40-full\log4net.xml" "..\release_studio"
copy "..\lib\VISA.NET Shared Components 5.8.0\Ivi.Visa.dll" "..\release_studio"
copy "..\lib\VISA.NET Shared Components 5.8.0\Ivi.Visa.xml" "..\release_studio"
copy "..\AILinkFactoryAuto\ConfigOfMes.ini" "..\release_studio"
copy "..\AILinkFactoryAuto\log4net.config" "..\release_studio"
copy "..\AILinkFactoryAuto\SetUp.ini" "..\release_studio"
pause